[package]
name = "learn-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
error-chain = {version = "0.12.4", features = ["default"]}
